---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luoyang1.
--- DateTime: 2019/5/8 8:49
---

-- Lua代码全局入口
function main()
    CS.UnityEngine.Debug.Log("hello lua~")
    test()
end

function test()
end

--- 逻辑帧更新
function FixedUpdate()
    --CS.TestXlua.Out("FixedUpdate")
end

--- LateUpdate
function LateUpdate()
    --CS.TestXlua.Out("LateUpdate")
end

local u = 0
--- 渲染帧更新
function RenderingUpdate()
    CS.TestXlua.Out("RenderingUpdate")
    u = u + 1
    local func = function()
        CS.UnityEngine.Debug.Log(u)
    end
    CS.TestXlua.Add(func)
end

function TestOneParamAction(str)
    CS.TestXlua.Out("TestOneParamAction : "..str)
end